# Generated by Django 5.2.13 on 2026-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pos_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('retail', 'Retail')], default='restaurant', max_length=20),
        ),
    ]
