# Generated by Django 5.2.13 on 2026-05-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_billed_by_order_cash_amount_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan_name',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
