# Generated by Django 5.2.13 on 2026-08-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderitem_is_printed_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pos_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant POS'), ('cafe', 'Cafe POS')], default='restaurant', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Store Admin'), ('cashier_restaurant', 'Restaurant Cashier'), ('cashier_cafe', 'Cafe Cashier')], default='cashier_restaurant', max_length=30),
        ),
    ]
