# Generated by Django 5.2.13 on 2026-08-29 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_company_pos_type_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('printer_type', models.CharField(choices=[('cash_bill', 'Cash / Bill Printer'), ('kot', 'KOT Kitchen/Station Printer')], default='kot', max_length=20)),
                ('ip_address', models.CharField(default='192.168.1.100', max_length=50)),
                ('port', models.IntegerField(default=9100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.printer'),
        ),
    ]
