# Generated by Django 5.2.13 on 2026-08-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='dine_in', max_length=20),
        ),
    ]
