# Generated by Django 5.2.13 on 2026-08-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card / Online'), ('split', 'Split (Cash + Card)')], default='cash', max_length=10),
        ),
    ]
