
from django.urls import path
from . import views
from . import api_views

urlpatterns = [
    path('', views.pos_dashboard, name='pos_dashboard'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('users/', views.manage_users, name='manage_users'),
    path('menu/', views.manage_menu, name='manage_menu'),
    path('tables/', views.manage_tables, name='manage_tables'),
    path('printers/', views.manage_printers, name='manage_printers'),
    path('orders/', views.order_history, name='order_history'),
    path('orders/<str:order_number>/', views.order_detail, name='order_detail'),
    path('kot/<str:order_number>/', views.kot_view, name='kot_view'),
    path('bill/<str:order_number>/', views.bill_view, name='bill_view'),
    path('sales/', views.sales_dashboard, name='sales_dashboard'),
    path('reports/export/', views.export_sales_report, name='export_sales_report'),
    path('super-admin/', views.super_admin_dashboard, name='super_admin_dashboard'),
    path('super-admin/create-company/', views.super_admin_create_company, name='super_admin_create_company'),
    path('super-admin/create-admin/', views.super_admin_create_admin, name='super_admin_create_admin'),
    path('super-admin/toggle-company/<int:company_id>/', views.super_admin_toggle_company, name='super_admin_toggle_company'),
    path('super-admin/renew-company/<int:company_id>/', views.super_admin_renew_company, name='super_admin_renew_company'),
    path('super-admin/edit-company/<int:company_id>/', views.super_admin_edit_company, name='super_admin_edit_company'),
    path('super-admin/delete-company/<int:company_id>/', views.super_admin_delete_company, name='super_admin_delete_company'),
    path('api/create-order/', views.create_order, name='create_order'),
    path('api/table-orders/<int:table_id>/', views.get_table_orders, name='get_table_orders'),
    path('api/active-orders/', views.get_active_orders, name='get_active_orders'),
    path('api/pay-order/<str:order_number>/', views.pay_order, name='pay_order'),
    path('api/transfer-table/', views.transfer_table, name='transfer_table'),
    path('api/invoice-order/<str:order_number>/', views.invoice_order, name='invoice_order'),
    path('api/printers/test/<int:printer_id>/', views.api_test_printer, name='api_test_printer'),
    path('api/print/kot/<str:order_number>/', views.api_print_kot, name='api_print_kot'),
    path('api/print/bill/<str:order_number>/', views.api_print_bill, name='api_print_bill'),
    path('api/companies/', api_views.get_companies, name='api_companies'),
    path('api/users/', api_views.manage_users_api, name='api_users'),
    path('api/menu/', api_views.get_menu, name='api_menu'),
    path('api/db-status/', views.api_db_status, name='api_db_status'),
]
